# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chingford & District Model Engineering Club
email: webmaster@cdmec.co.uk
description: >
  Interested in learning model engineering or getting involved
  with a miniature steam railway, then join Chingford &amp; District Model
  Engineering Club.
keywords: >
  chingford, and, &amp;, district, model, engineering, club, society,
  web site, miniature railway, steam railway, steam trains, model engineering,
  london, UK, north nondon, britain, railway, E4, carriage, wagon, historic,
  vehicle, clocks, trains, public, train rides, traction engines, static engines,
  stationery engines, stationery, model making, workshop, engineering club, society,
  cdmec, cadmec, c&amp;dmec, CDMEC, C&amp;DMEC, Chingford miniature trains,
  Ridgeway park trains
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cdmec.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-assets

assets:
  compress:
    css:  sass
    js:   uglifier
